server:
  port: 8889
spring:
  sharding-sphere:
    props:
      sql:
        show: true
    datasource:
      names: master-0,slave-0
      master-0: # 数据库 master-0, 包含连接池、驱动、地址、用户名、密码
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3336/test?serverTimezone=UTC
        username: root
        password: 123456

      slave-0: # 数据库 slave-0, 包含连接池、驱动、地址、用户名、密码
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3337/test?serverTimezone=UTC
        username: root
        password: 123456
      # 指定数据库分布情况，数据库里面表分布情况
    sharding:
      master-slave-rules:
        ds0: # 主从关系, 读写分离
          master-data-source-name: master-0
          slave-data-source-names:
            - slave-0
      tables: # 分表规则
        dict:
          actual-data-nodes: ds0.dict   # 这里使用主从关系
          key-generator: # 表中主键生成策略
            column: id           # 分库依赖的列
            type: UUID
          table-strategy: # 分片策略
            inline: # 不支持范围查询
              sharding-column: id
              algorithm-expression: dict
