server:
  port: 8888

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master: # 数据库 master-0, 包含连接池、驱动、地址、用户名、密码
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3336/test?serverTimezone=UTC
          username: root
          password: 123456

        slave-0: # 数据库 slave-0, 包含连接池、驱动、地址、用户名、密码
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3337/test?serverTimezone=UTC
          username: root
          password: 123456