server:
  port: 8888
spring:
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-mate:
  cert:
    grant:  授予单位
    license: SM/hy2HGmqRZIw7NE5i1vKIiHOQLGXGymokyRCkR+TYuNZuVTdYiESr41OZiYyDkH095+Y5Ifc7tCyVeGi3qrsnyninzgcmvZsUKDl9kQYXzvbt/R7UMj6yqchPsZYf0UQ0mvRyoja1ljXiqbz49qrqXy0q1umWBEzrbH7QjE55M/bnABovM5ljCoENfY2b0EvSaJCUeqeAAxM3K6VrBo0YI4rz9Uo28AXhRgAyaI0QgMy+APM5bCdp9GEXHXYEyApMDvRCqWLfh5WZVdDWD5PZouQL3TKD3kqEf4k+Z1GkrVtHDS9mugpbSP533dHd9O+NF1KpOhkN0lVojrJ21Bg==

  sharding:
    health: true # 健康检查
    primary: mysql # 默认数据源
    datasource:
      mysql:
        - key: master0
          cluster: master
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3336/test?serverTimezone=UTC
          username: root
          password: 123456

        - key: slave01
          cluster: slave
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3337/test?serverTimezone=UTC
          username: root
          password: 123456